version: '3'

services:
  practice2_container:
    image: practice2_image
    container_name: practice2_container
    ports:
      - "41080:9000"
      - "41081:9001"
    volumes:
      - /home/disk5/taewan/study/practice2/demo3/logs:/base/logs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # GPU 접근 설정
    environment:
      - NVIDIA_VISIBLE_DEVICES=15  # GPU 15번만 사용 
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - REDIS_URL=redis://redis_container:6379/0

    runtime: nvidia  # NVIDIA 런타임 사용
    networks:
      - practice2_network

  redis_container:
    image: redis
    container_name: redis_container
    ports:
      - "41083:6379"
    networks:
      - practice2_network

networks:
  practice2_network:
    driver: bridge
