version: '3'

services:
  practice3_container:
    image: practice2_image
    container_name: practice2_container
    ports:
      - "41080:9000"
      - "41081:9001"
    volumes:
      - /home/disk5/taewan/study/practice2/demo3/prod/logs:/base/logs
      - /home/disk5/taewan/study/practice2/demo3/prod/data/video_data:/base/data/video_data
      - /home/disk5/taewan/study/practice2/demo3/prod/app/src:/base/app/src

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # GPU 접근 설정
    environment:
      - NVIDIA_VISIBLE_DEVICES=15  # GPU 15번만 사용 
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - REDIS_URL=redis://redis2_container:6379/0
      - PYTHONPATH=$PYTHONPATH:/base/app:/base/app/src


    runtime: nvidia  # NVIDIA 런타임 사용
    networks:
      - practice2_network

  redis3_container:
    image: redis
    container_name: redis2_container
    ports:
      - "41083:6379"
    networks:
      - practice2_network

  mysql2_container:
    image: mysql:latest
    container_name: mysql2_container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3307:3306"
    volumes:
      - /home/disk5/taewan/study/practice2/demo3/prod/data/mysql_data:/var/lib/mysql
    networks:
      - practice2_network

networks:
  practice2_network:
    driver: bridge
